services:
- docker
language: java
script:
- mvn package
deploy:
- provider: script
  script: bash docker-push.sh
  on:
    branch: master
- provider: releases
  api_key:
    secure: R0bB7XctNSlqgQLY73yqzlp9/bQf55Uyn4D3ZGeH52dIX7yq1vYA3bTReRnJMX5mLPdF+Of77Dd9bL0Db6sHxAtKODggk/Ab4bUr+ueroDiT/ApzODESX537iTFaarDbIx96AmJADZL3H3hSbtgadmBAr6gX7alEFGnZj7eUrRZjCyBYA5XhJrH5bgfuyCUUF/CjxV2kpeboE6cbuzD/RjLBWlP+xO4pEwmjGgqWFPWf5jLWLsELwhVO4MqcSy+5XrRQIdtdEcYJBz6Op6FIxMW4rrWVMrcjrXD3BjKNTX3s6U3cdjKI4Biz8TQvBdlFzGQtdcizYkLFFNfExeVLTaZSvwXumYwHeMQ82IktQ9xqGoApWjrK+hOfhSJ4XH+PJqfhAsfa1d3LCqua8T79GCjvSGM8pMNXh17jUm+eVqXr4qkesWskf1J4JMBSRYLt5unOd5ed6ztPVt89IvPVXuZXgzLhAYWpzsLLv00o1PPZw7X53hLP+Yus7DBlTgCgpx9v4PfE32jc6s1FLbr+nUmC3xWmzgH1OfGit34IpD0hc1sdUDggOgK2i2/FGcu5k7QZr1QafPWBdDlkFfVoSEMCbt70+TXzdm0oLA26m0VmBGrViNRPI3SS84Z1h4PJQUd1iQgKhmzCcnyxRCD9mIwTTcQWQj4Cuubz4dcz5aQ=
  file_glob: true
  file: portal/target/*.war
  skip_cleanup: true
  on:
    tags: true
env:
  global:
  - secure: vWjGmOsFGdw0P5rp9q8TJrVtz86X5rwWfmghssqgaS+VKYq1RgFpdxUFq4uIviAbdsiDdsTZEW8jSIX+Qyx2hgbW8KJ6X+3AqreGuRvcj0rnafMKszer432wH1kyzQLWS7C8tcLzGeO04YgwjaVjUjkEIlG2gqyZeWDjeh8p1flpCtAMqnNAF6LK7wy9BRNdUUWy1+Y5KZgDaUcyBBTtj5L9HaN2h0GFu0IPvZGJuyoIvWiu/7RhRmcP73RMOg/37g51ilXx0xsoKJSZMHzI19WiaiM4hY0J3s5iS8LmTRE5RFW6oO4xUEq7F0CdK3IAGRUZ4/U+iZhbwbn8bEd/0jpCvxXGLa6KiT09SxJuAHlN3zYG5MhL2bFeQyWTVk6PIgaWbB2wW9KtbxAWp/u1lXZJnRg3vCCQ/RXPP2lYzr+uDHoXHTuNRees5VthtsjNziNDqiffOQ2PjPYXUvl4KM9UJnC/jCRe2MzA6vINzNyL4rTRvyd7+5dp142df+u94CDx2m3ktLW8A/2taHQTfeL4K9vrk8QIsYWVHJ2Xojesbo0FYGKeTZJPN7Rwwl53cp8GhKzda/0FWa5uhrQL7QCiyHRboSZeDps5RtL3eVu35DkqM+TqHD34KsLTJt0m8vx45d4SsLkXTpV8vHk9w2ZSaGgC/nK8kmvyMbHKN8Y=
  - secure: npgzoj/86saSQwmB2orxddcEhpMpXMxzeSAEKz9336iHljTGmrO7UL3/3ey+qmlvzwQnhvhIY1T5Xcgt+iW1VM98rCBA2VvmWWg2Qh2ISrmXuMKKDkzY+v0j2LEgEhB1ZjDdNk8l2qnWIRnxtAGmdBWQohGMNtgHUY6dhVntiii/CbbjtRFAaLXLHtb7m8QLAWpLGXHQJyEFYr9MImZzcFwITC6IvBa933WzAZ6OcDd3Hy7khep7YM0yRxAT+IsNzB3OJsl50AJTl89CqPfxmVr4Y9s222jIMiR9f7OnjjGs0H/tEeDL3aAUCqBDTu/6VFSuaawLpj9Qpktv+kZdb7mBRPakiuELG8TvlWCNx+f//uD5YlExWreixNlMr+GUkiwEoQGkzxDB+Loe+pCTlGEWQ1F+rkPjfyV0sjPaPKqTMmWdgZexlWCPVBKEbR6vLbEu+8UfSYp6p9x+f2xCh4ErtCgYPmb0FBLmDQ83iFk1mh0BF7CWoArMC8eWs1AgtiyLdM435lqDgreHghN4/U/ASM6CmtvWSTVgjcvkIEv1Gjhk6hXH5ENZYWkF5qvpjFpxpBloG+H+/DohUFuaIcJTlpEAJEgGP+TiWDKL4akEeG01ddmn81rwZjdzVgYXPd97K6XSt4QRocvrhaVa8ha9MYl/5odUY9DBmsVUZMI=
