version: '3'

services:
  wings:
    image: "mosorio/wings:dev"
    build:
      context: .
      dockerfile: wings-docker/docker/default/Dockerfile
    environment:
      WINGS_MODE: dind
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 7072:8080

volumes:
  wings_data: